version: '3.8'
services:
  db:
    image: postgres:latest 
    restart: always 
    environment:
      POSTGRES_USER: luquinhas3264 
      POSTGRES_PASSWORD: 3264 
      POSTGRES_DB: viceversadb 
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data 

  pgadmin: 
    image: dpage/pgadmin4 
    container_name: pgadmin_container 
    restart: always 
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com 
      PGADMIN_DEFAULT_PASSWORD: adminpassword 
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80" 
    depends_on: 
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin_data: 